[project]
name = "alm"
version = "0.1.0"
description = "Ansible Log Monitoring"
readme = "README.md"
authors = [
    { name = "Itay Katav", email = "ikatav@redhat.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/alm"]

[project.optional-dependencies]
dev = [
    "black>=24.2.0",
    "isort>=6.0.0",
    "flake8>=6.0.0",
    "pre-commit>=3.0.0",
]