promtail:
  podSecurityContext:
    runAsNonRoot: false
    runAsUser: 0
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    runAsNonRoot: false
    runAsUser: 0
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  # Avoid using hostPath volumes if possible; use PVCs or emptyDir instead
  # If hostPath is required, ensure it's justified and restricted
  volumes: []
  volumeMounts: []

grafana:
  podSecurityContext:
    runAsNonRoot: false
    runAsUser: 0
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    runAsNonRoot: false
    runAsUser: 0
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

loki:
  podSecurityContext:
    runAsNonRoot: false
    runAsUser: 0
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    runAsNonRoot: false
    runAsUser: 0
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL