{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "backend.fullname" . }}-deployment-reader
  labels:
    {{- include "backend.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "backend.fullname" . }}-deployment-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "backend.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}

